# Utiliser avec kubectl apply -f secret.yaml -n airflow

apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: airflow
data:
  GIT_SYNC_USERNAME: changethis # echo -n "USERNAME" | base64
  GIT_SYNC_PASSWORD: changethis # echo -n "PASSWORD" | base64




---

apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: airflow
type: Opaque
data:
  access_key: changethis #echo -n "minio-name" | base64
  secret_key: changethis # echo -n "minio-secret" | base64
  s3_connection_uri: changethis
  # s3://minio-name:minio-secret@myminio-hl.minio-tenant1.svc.cluster.local:9000/BUCKETNAME
